import type {
  CssPreviewConfig,
  PreviewPresetStyleMap,
  PreviewStyleTokenMap,
} from '@/features/handbook/css/common/types';

const presetStyleMap: PreviewPresetStyleMap = {
  'position-offset-condition': {
    container: {
      position: 'relative',
      display: 'block',
      width: '100%',
      minHeight: '260px',
      padding: '12px',
      border: '1px dashed #64748b',
      borderRadius: '8px',
      backgroundColor: '#0f172a',
    },
    itemA: {
      position: 'static',
      top: '24px',
      left: '24px',
      width: '180px',
      minHeight: '72px',
      background: '#2563eb',
      color: '#f8fafc',
      zIndex: 2,
    },
    itemB: {
      position: 'static',
      width: '220px',
      minHeight: '72px',
      marginTop: '12px',
      background: '#334155',
      color: '#f8fafc',
    },
  },
  'position-relative-flow': {
    container: {
      position: 'relative',
      display: 'block',
      width: '100%',
      minHeight: '260px',
      padding: '12px',
      border: '1px dashed #64748b',
      borderRadius: '8px',
      backgroundColor: '#0f172a',
    },
    itemA: {
      position: 'relative',
      top: '24px',
      left: '24px',
      width: '180px',
      minHeight: '72px',
      background: '#0ea5e9',
      color: '#f8fafc',
      zIndex: 2,
    },
    itemB: {
      position: 'static',
      width: '220px',
      minHeight: '72px',
      marginTop: '12px',
      background: '#334155',
      color: '#f8fafc',
    },
  },
  'position-absolute-badge-layout': {
    container: {
      position: 'relative',
      display: 'block',
      width: '100%',
      minHeight: '300px',
      padding: '12px',
      overflow: 'hidden',
      border: '1px dashed #64748b',
      borderRadius: '8px',
      backgroundColor: '#0f172a',
    },
    itemA: {
      position: 'absolute',
      top: '12px',
      right: '12px',
      left: 'auto',
      bottom: 'auto',
      width: '94px',
      minHeight: '40px',
      borderRadius: '9999px',
      background: '#f59e0b',
      color: '#111827',
      zIndex: 6,
      fontWeight: 800,
    },
    itemB: {
      position: 'static',
      width: '100%',
      minHeight: '160px',
      background: '#1e293b',
      color: '#f8fafc',
    },
    itemC: {
      position: 'static',
      width: '100%',
      minHeight: '112px',
      marginTop: '12px',
      background: '#334155',
      color: '#f8fafc',
    },
  },
  'position-fixed-fab': {
    container: {
      position: 'relative',
      display: 'block',
      width: '100%',
      minHeight: '240px',
      maxHeight: '240px',
      overflowY: 'auto',
      padding: '12px',
      border: '1px dashed #64748b',
      borderRadius: '8px',
      backgroundColor: '#0f172a',
      transform: 'translateZ(0)',
      isolation: 'isolate',
    },
    itemA: {
      position: 'fixed',
      right: '16px',
      left: 'auto',
      bottom: '16px',
      top: 'auto',
      width: '84px',
      minHeight: '52px',
      borderRadius: '9999px',
      background: '#22c55e',
      color: '#052e16',
      zIndex: 999,
      fontWeight: 800,
    },
    itemB: {
      position: 'static',
      width: '100%',
      minHeight: '180px',
      marginBottom: '10px',
      background: '#1e293b',
      color: '#f8fafc',
    },
    itemC: {
      position: 'static',
      width: '100%',
      minHeight: '180px',
      marginBottom: '10px',
      background: '#334155',
      color: '#f8fafc',
    },
  },
  'position-sticky-threshold': {
    container: {
      position: 'relative',
      display: 'block',
      width: '100%',
      minHeight: '220px',
      maxHeight: '220px',
      overflowY: 'auto',
      padding: '8px',
      border: '1px dashed #64748b',
      borderRadius: '8px',
      backgroundColor: '#0f172a',
    },
    itemA: {
      position: 'sticky',
      top: '0px',
      width: '100%',
      minHeight: '56px',
      marginBottom: '8px',
      background: '#0ea5e9',
      color: '#f8fafc',
      zIndex: 6,
    },
    itemB: {
      position: 'static',
      width: '100%',
      minHeight: '120px',
      marginBottom: '8px',
      background: '#475569',
      color: '#f8fafc',
    },
    itemC: {
      position: 'static',
      width: '100%',
      minHeight: '120px',
      marginBottom: '8px',
      background: '#334155',
      color: '#f8fafc',
    },
  },
};

const tokenStyleMap: PreviewStyleTokenMap = {
  'position-offset-static': { itemA: { position: 'static' } },
  'position-offset-relative': { itemA: { position: 'relative' } },
  'position-offset-top-0': { itemA: { top: '0px' } },
  'position-offset-top-24': { itemA: { top: '24px' } },
  'position-offset-top-56': { itemA: { top: '56px' } },
  'position-offset-left-0': { itemA: { left: '0px' } },
  'position-offset-left-24': { itemA: { left: '24px' } },
  'position-offset-left-56': { itemA: { left: '56px' } },

  'position-relative-top-0': { itemA: { top: '0px' } },
  'position-relative-top-24': { itemA: { top: '24px' } },
  'position-relative-top-56': { itemA: { top: '56px' } },
  'position-relative-left-0': { itemA: { left: '0px' } },
  'position-relative-left-24': { itemA: { left: '24px' } },
  'position-relative-left-56': { itemA: { left: '56px' } },

  'position-absolute-badge-static': {
    itemA: {
      position: 'static',
      top: 'auto',
      right: 'auto',
      left: 'auto',
      bottom: 'auto',
      marginBottom: '8px',
    },
  },
  'position-absolute-badge-absolute': {
    itemA: {
      position: 'absolute',
      top: '12px',
      right: '12px',
      left: 'auto',
      bottom: 'auto',
      marginBottom: '0px',
    },
  },
  'position-absolute-badge-top-right': {
    itemA: {
      top: '12px',
      right: '12px',
      left: 'auto',
      bottom: 'auto',
    },
  },
  'position-absolute-badge-top-left': {
    itemA: {
      top: '12px',
      left: '12px',
      right: 'auto',
      bottom: 'auto',
    },
  },
  'position-absolute-badge-bottom-right': {
    itemA: {
      top: 'auto',
      right: '12px',
      left: 'auto',
      bottom: '12px',
    },
  },

  'position-fixed-fab-static': {
    itemA: {
      position: 'static',
      top: 'auto',
      right: 'auto',
      left: 'auto',
      bottom: 'auto',
      marginBottom: '10px',
    },
  },
  'position-fixed-fab-fixed': {
    itemA: {
      position: 'fixed',
      top: 'auto',
      right: '16px',
      left: 'auto',
      bottom: '16px',
      marginBottom: '0px',
    },
  },
  'position-fixed-fab-right': {
    itemA: {
      right: '16px',
      left: 'auto',
    },
  },
  'position-fixed-fab-left': {
    itemA: {
      right: 'auto',
      left: '16px',
    },
  },
  'position-fixed-fab-bottom': {
    itemA: {
      bottom: '16px',
      top: 'auto',
    },
  },
  'position-fixed-fab-top': {
    itemA: {
      bottom: 'auto',
      top: '16px',
    },
  },

  'position-sticky-mode-relative': { itemA: { position: 'relative' } },
  'position-sticky-mode-sticky': { itemA: { position: 'sticky' } },
  'position-sticky-top-0': { itemA: { top: '0px' } },
  'position-sticky-top-24': { itemA: { top: '24px' } },
  'position-sticky-top-48': { itemA: { top: '48px' } },
};

export const positionPreviewConfig: CssPreviewConfig = {
  presetStyleMap,
  tokenStyleMap,
};
